//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookModel
    {
        public int id { get; set; }
        public Nullable<System.DateTime> test_time { get; set; }
        public string bookName { get; set; }
        public string summary { get; set; }
        public string BookType { get; set; }
        public string BookLanguage { get; set; }
    }
}
